---
- hosts: kubernetes-master
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  #environment:
  #      http_proxy: http://10.222.1.1:8080
  #      https_proxy: http://10.222.1.1:8080
  roles:
    - master 
    
- hosts: kubernetes-edge
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: no
  #environment:
  #      http_proxy: http://10.222.1.1:8080
  #      https_proxy: http://10.222.1.1:8080
  roles:
    - edge
