---
# tasks disable "SE LINUX"
- name: == SYSTEM == Turn Off SELinux
  selinux:
    state: disabled

# tasks install "Docker"
- name: == YUM == Uninstall old versions
  yum: name={{ item }} state=absent
  with_items:
   - docker
   - docker-common
   - container-selinux
   - docker-selinux
   - docker-engine

- name: == YUM == Install Docker utility
  yum: name={{ item }} state=lastest
  with_items:
   - yum-utils
   - device-mapper-persistent-data
   - lvm2

- name: Install add Docker repo
  yum_repository:
    name: Docker
    description: Docker repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    gpgcheck: no

- name: == YUM == Install Docker
  yum: name={{ item }} state=lastest
  with_items:
   - docker

- name: == Service Start == start Docker
- service:
    name: docker
    state: started
    enabled: yes

# tasks install "Kubectl"


#  - yum: name=kubelet state=latest
#  - yum: name=kubeadm state=latest
#  - yum: name=kubectl state=latest
#  - yum: name=kubernetes-cni state=latest
#  - service:
#      name: kubelet
#      state: started
#      enabled: yes
      

#- name: == YUM == Install Docker

#- name: == REPO == Add Kubernetes Repository
#  copy: src=kubernetes.repo dest=/etc/yum.repos.d/kubernetes.repo

#- name: == YUM == Install Kubernetes
#  yum: name={{ item }} state=latest
#  with_items: "{{ kubernetes_items }}"

#- name: == SERVICE == Enable/Start Kubelet Service
#  raw: systemctl enable kubelet && systemctl start kubelet

#- name: == SERVICE == Make sure Kubelet is running
#  service:
#    name: kubelet
#    enabled: yes
#    state: started
